pipeline {


    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    

    environment{
        cluster = "vproprod"
        service = "vproprodsvc"
    }

    stage('Deploy  ECS to prod') {
            steps{
                withAWS(credentials: 'awscresd', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
}